<?xml version="1.0"?>
<package format="2">
  <name>corridor_generator</name>
  <version>0.0.1</version>
  <description>Interactive flight corridor generator using DecompROS</description>

  <maintainer email="user@todo.todo">User</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  
  <depend>roscpp</depend>
  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>decomp_ros_msgs</depend>
  <depend>decomp_ros_utils</depend>
  <depend>tf</depend>
  <depend>onboard_detector</depend>

  <export>
  </export>
</package>

